// Verbatim port of the upstream cypress fake-cluster generators (rancher/dashboard
// cypress/e2e/blueprints/nav/fake-cluster.ts @ master 2026-06-10, commits 3f55a6e9..db1dd2e).
// Mechanical transforms only: localhost port, revision constant name, export keywords.
// Do not hand-edit the data; re-extract from upstream on the next sync.
import { SAFE_RESOURCE_REVISION } from '../blueprint.utils';

export const MACHINE_POOL_ID = '995mj';
export const CLOUD_CRED_ID = 'srb7v';
const namespace = 'fleet-default';

export function generateProvClusterObj(provClusterId: string, mgmtClusterId: string) {
  return {
    id: `${namespace}/${provClusterId}`,
    type: 'provisioning.cattle.io.cluster',
    links: {
      remove: `https://localhost:8443/v1/provisioning.cattle.io.clusters/${namespace}/${provClusterId}`,
      self: `https://localhost:8443/v1/provisioning.cattle.io.clusters/${namespace}/${provClusterId}`,
      update: `https://localhost:8443/v1/provisioning.cattle.io.clusters/${namespace}/${provClusterId}`,
      view: `https://localhost:8443/apis/provisioning.cattle.io/v1/namespaces/${namespace}/clusters/${provClusterId}`,
    },
    apiVersion: 'provisioning.cattle.io/v1',
    kind: 'Cluster',
    metadata: {
      annotations: { 'field.cattle.io/creatorId': 'user-lfv6k' },
      creationTimestamp: '2024-03-07T15:45:25Z',
      fields: [provClusterId, 'true', `${provClusterId}-kubeconfig`],
      finalizers: [
        'wrangler.cattle.io/provisioning-cluster-remove',
        'wrangler.cattle.io/rke-cluster-remove',
        'wrangler.cattle.io/cloud-config-secret-remover',
      ],
      generation: 3,
      name: provClusterId,
      namespace: `${namespace}`,
      relationships: [
        {
          toId: `${namespace}/crt-${provClusterId}-cluster-owner`,
          toType: 'rbac.authorization.k8s.io.role',
          rel: 'owner',
          state: 'active',
          message: 'Resource is current',
        },
        {
          toId: `${namespace}/crt-${provClusterId}-cluster-admin`,
          toType: 'rbac.authorization.k8s.io.role',
          rel: 'owner',
          state: 'active',
          message: 'Resource is current',
        },
        {
          toId: `${namespace}/nc-${provClusterId}-pool1-${MACHINE_POOL_ID}`,
          toType: 'rke-machine-config.cattle.io.digitaloceanconfig',
          rel: 'owner',
          state: 'active',
          message: 'Resource is current',
        },
        {
          toId: `${namespace}/${provClusterId}`,
          toType: 'cluster.x-k8s.io.cluster',
          rel: 'owner',
          state: 'provisioned',
        },
        {
          toId: `${namespace}/crt-${provClusterId}-cluster-member`,
          toType: 'rbac.authorization.k8s.io.role',
          rel: 'owner',
          state: 'active',
          message: 'Resource is current',
        },
        {
          toId: `${namespace}/${provClusterId}-managed-system-agent`,
          toType: 'fleet.cattle.io.bundle',
          rel: 'owner',
          state: 'active',
          message: 'Resource is Ready',
        },
        {
          toId: `${namespace}/${provClusterId}-managed-system-upgrade-c-e07cc`,
          toType: 'management.cattle.io.managedchart',
          rel: 'owner',
          state: 'active',
          message: 'Resource is Ready',
        },
        {
          toId: `${namespace}/r-cluster-${provClusterId}-view-p-jwd4v-creator-project-7edf69`,
          toType: 'rbac.authorization.k8s.io.rolebinding',
          rel: 'owner',
          state: 'active',
          message: 'Resource is current',
        },
        {
          toId: `${namespace}/${provClusterId}`,
          toType: 'fleet.cattle.io.cluster',
          rel: 'applies',
          state: 'active',
          message: 'Resource is Ready',
        },
        {
          toId: `${namespace}/crt-${provClusterId}-nodes-view`,
          toType: 'rbac.authorization.k8s.io.role',
          rel: 'owner',
          state: 'active',
          message: 'Resource is current',
        },
        {
          toId: `${namespace}/r-cluster-${provClusterId}-view`,
          toType: 'rbac.authorization.k8s.io.role',
          rel: 'owner',
          state: 'active',
          message: 'Resource is current',
        },
        {
          toId: `${namespace}/r-cluster-${provClusterId}-view-p-rs8ps-creator-project-8aae6c`,
          toType: 'rbac.authorization.k8s.io.rolebinding',
          rel: 'owner',
          state: 'active',
          message: 'Resource is current',
        },
        {
          toId: `${mgmtClusterId}/${mgmtClusterId}-${namespace}-owner`,
          toType: 'management.cattle.io.clusterroletemplatebinding',
          rel: 'applies',
          state: 'active',
          message: 'Resource is current',
        },
        {
          toId: `${namespace}/crt-${provClusterId}-nodes-manage`,
          toType: 'rbac.authorization.k8s.io.role',
          rel: 'owner',
          state: 'active',
          message: 'Resource is current',
        },
        {
          toId: mgmtClusterId,
          toType: 'management.cattle.io.cluster',
          rel: 'applies',
          state: 'active',
          message: 'Resource is Ready',
        },
        {
          toId: `${namespace}/${provClusterId}-kubeconfig`,
          toType: 'secret',
          rel: 'owner',
          state: 'active',
          message: 'Resource is always ready',
        },
      ],
      resourceVersion: SAFE_RESOURCE_REVISION,
      state: {
        error: false,
        message: 'Resource is Ready',
        name: 'active',
        transitioning: false,
      },
      uid: '326aa188-e66f-4cf0-8f54-9fc47e4c5d92',
    },
    spec: {
      cloudCredentialSecretName: `cattle-global-data:cc-${CLOUD_CRED_ID}`,
      kubernetesVersion: 'v1.27.10+rke2r1',
      localClusterAuthEndpoint: {},
      rkeConfig: {
        chartValues: { 'rke2-calico': {} },
        etcd: {
          snapshotRetention: 5,
          snapshotScheduleCron: '0 */5 * * *',
        },
        machineGlobalConfig: {
          cni: 'calico',
          'disable-kube-proxy': false,
          'etcd-expose-metrics': false,
          'ingress-controller': 'ingress-nginx',
        },
        machinePoolDefaults: {},
        machinePools: [
          {
            controlPlaneRole: true,
            drainBeforeDelete: true,
            dynamicSchemaSpec:
              '{"resourceFields":{"accessToken":{"type":"password","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"Digital Ocean access token"},"backups":{"type":"boolean","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"enable backups for droplet"},"image":{"type":"string","default":{"stringValue":"ubuntu-20-04-x64","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"Digital Ocean Image"},"ipv6":{"type":"boolean","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"enable ipv6 for droplet"},"monitoring":{"type":"boolean","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"enable monitoring for droplet"},"privateNetworking":{"type":"boolean","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"enable private networking for droplet"},"region":{"type":"string","default":{"stringValue":"nyc3","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"Digital Ocean region"},"size":{"type":"string","default":{"stringValue":"s-1vcpu-1gb","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"Digital Ocean size"},"sshKeyContents":{"type":"password","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"File contents for sshKeyContents"},"sshKeyFingerprint":{"type":"string","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"SSH key fingerprint"},"sshPort":{"type":"string","default":{"stringValue":"22","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"SSH port"},"sshUser":{"type":"string","default":{"stringValue":"root","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"SSH username"},"tags":{"type":"string","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"comma-separated list of tags to apply to the Droplet"},"userdata":{"type":"string","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"File contents for userdata"}}}',
            etcdRole: true,
            machineConfigRef: {
              kind: 'DigitaloceanConfig',
              name: `nc-${provClusterId}-pool1-${MACHINE_POOL_ID}`,
            },
            name: 'pool1',
            quantity: 1,
            unhealthyNodeTimeout: '0s',
            workerRole: true,
          },
        ],
        machineSelectorConfig: [{ config: { 'protect-kernel-defaults': false } }],
        registries: {
          configs: {
            reg1: { authConfigSecretName: 'registryconfig-auth-reg1' },
            reg2: { authConfigSecretName: 'registryconfig-auth-reg2' },
          },
        },
        upgradeStrategy: {
          controlPlaneConcurrency: '1',
          controlPlaneDrainOptions: {
            deleteEmptyDirData: true,
            disableEviction: false,
            enabled: false,
            force: false,
            gracePeriod: -1,
            ignoreDaemonSets: true,
            ignoreErrors: false,
            postDrainHooks: null,
            preDrainHooks: null,
            skipWaitForDeleteTimeoutSeconds: 0,
            timeout: 120,
          },
          workerConcurrency: '1',
          workerDrainOptions: {
            deleteEmptyDirData: true,
            disableEviction: false,
            enabled: false,
            force: false,
            gracePeriod: -1,
            ignoreDaemonSets: true,
            ignoreErrors: false,
            postDrainHooks: null,
            preDrainHooks: null,
            skipWaitForDeleteTimeoutSeconds: 0,
            timeout: 120,
          },
        },
      },
    },
    status: {
      agentDeployed: true,
      clientSecretName: `${provClusterId}-kubeconfig`,
      clusterName: mgmtClusterId,
      conditions: [
        {
          error: false,
          lastUpdateTime: '2024-03-07T15:52:44Z',
          status: 'False',
          transitioning: false,
          type: 'Reconciling',
        },
        {
          error: false,
          lastUpdateTime: '2024-03-07T15:45:25Z',
          status: 'False',
          transitioning: false,
          type: 'Stalled',
        },
        {
          error: false,
          lastUpdateTime: '2024-03-07T15:52:44Z',
          status: 'True',
          transitioning: false,
          type: 'Created',
        },
        {
          error: false,
          lastUpdateTime: '2024-03-07T15:52:47Z',
          status: 'True',
          transitioning: false,
          type: 'RKECluster',
        },
        {
          error: false,
          lastUpdateTime: '2024-03-07T15:45:26Z',
          status: 'True',
          transitioning: false,
          type: 'BackingNamespaceCreated',
        },
        {
          error: false,
          lastUpdateTime: '2024-03-07T15:45:26Z',
          status: 'True',
          transitioning: false,
          type: 'DefaultProjectCreated',
        },
        {
          error: false,
          lastUpdateTime: '2024-03-07T15:45:26Z',
          status: 'True',
          transitioning: false,
          type: 'SystemProjectCreated',
        },
        {
          error: false,
          lastUpdateTime: '2024-03-07T15:45:26Z',
          status: 'True',
          transitioning: false,
          type: 'InitialRolesPopulated',
        },
        {
          error: false,
          lastUpdateTime: '2024-03-07T15:52:29Z',
          status: 'True',
          transitioning: false,
          type: 'Connected',
        },
        {
          error: false,
          lastUpdateTime: '2024-03-07T15:45:30Z',
          status: 'True',
          transitioning: false,
          type: 'CreatorMadeOwner',
        },
        {
          error: false,
          lastUpdateTime: '2024-03-07T15:52:47Z',
          status: 'True',
          transitioning: false,
          type: 'Updated',
        },
        {
          error: false,
          lastUpdateTime: '2024-03-07T15:52:47Z',
          status: 'True',
          transitioning: false,
          type: 'Provisioned',
        },
        {
          error: false,
          lastUpdateTime: '2024-03-07T15:52:47Z',
          status: 'True',
          transitioning: false,
          type: 'Ready',
        },
        {
          error: false,
          lastUpdateTime: '2024-03-07T15:45:34Z',
          status: 'True',
          transitioning: false,
          type: 'NoDiskPressure',
        },
        {
          error: false,
          lastUpdateTime: '2024-03-07T15:45:34Z',
          status: 'True',
          transitioning: false,
          type: 'NoMemoryPressure',
        },
        {
          error: false,
          lastUpdateTime: '2024-03-07T15:45:34Z',
          status: 'True',
          transitioning: false,
          type: 'SecretsMigrated',
        },
        {
          error: false,
          lastUpdateTime: '2024-03-07T15:45:34Z',
          status: 'True',
          transitioning: false,
          type: 'ServiceAcnamespaceSecretsMigrated',
        },
        {
          error: false,
          lastUpdateTime: '2024-03-07T15:45:34Z',
          status: 'True',
          transitioning: false,
          type: 'RKESecretsMigrated',
        },
        {
          error: false,
          lastUpdateTime: '2024-03-07T15:45:35Z',
          status: 'True',
          transitioning: false,
          type: 'ACISecretsMigrated',
        },
        {
          error: false,
          lastUpdateTime: '2024-03-07T15:51:59Z',
          status: 'True',
          transitioning: false,
          type: 'GlobalAdminsSynced',
        },
        {
          error: false,
          lastUpdateTime: '2024-03-07T15:52:04Z',
          status: 'True',
          transitioning: false,
          type: 'SystemAccountCreated',
        },
        {
          error: false,
          lastUpdateTime: '2024-03-07T15:52:17Z',
          status: 'True',
          transitioning: false,
          type: 'AgentDeployed',
        },
        {
          error: false,
          lastUpdateTime: '2024-03-07T15:52:44Z',
          status: 'True',
          transitioning: false,
          type: 'Waiting',
        },
      ],
      fleetWorkspaceName: `${namespace}`,
      observedGeneration: 3,
      ready: true,
    },
  };
}

export function generateMgmtClusterObj(provClusterId: string, mgmtClusterId: string) {
  return {
    id: mgmtClusterId,
    type: 'management.cattle.io.cluster',
    links: {
      log: `https://localhost:8443/v1/management.cattle.io.clusters/${mgmtClusterId}?link=log`,
      projects: `https://localhost:8443/v1/management.cattle.io.clusters/${mgmtClusterId}?link=projects`,
      remove: 'blocked',
      schemas: `https://localhost:8443/v1/management.cattle.io.clusters/${mgmtClusterId}?link=schemas`,
      self: `https://localhost:8443/v1/management.cattle.io.clusters/${mgmtClusterId}`,
      shell: `wss://localhost:8443/v3/clusters/${mgmtClusterId}?shell=true`,
      subscribe: `https://localhost:8443/v1/management.cattle.io.clusters/${mgmtClusterId}?link=subscribe`,
      update: 'blocked',
      view: `https://localhost:8443/v1/management.cattle.io.clusters/${mgmtClusterId}`,
    },
    actions: {
      apply: `https://localhost:8443/v1/management.cattle.io.clusters/${mgmtClusterId}?action=apply`,
      enableMonitoring: `https://localhost:8443/v3/clusters/${mgmtClusterId}?action=enableMonitoring`,
      generateKubeconfig: `https://localhost:8443/v3/clusters/${mgmtClusterId}?action=generateKubeconfig`,
      importYaml: `https://localhost:8443/v3/clusters/${mgmtClusterId}?action=importYaml`,
    },
    apiVersion: 'management.cattle.io/v3',
    kind: 'Cluster',
    metadata: {
      annotations: {
        'authz.management.cattle.io/creator-role-bindings':
          '{"created":["cluster-owner"],"required":["cluster-owner"]}',
        'authz.management.cattle.io/initial-sync': 'true',
        'field.cattle.io/creatorId': 'user-lfv6k',
        'lifecycle.cattle.io/create.cluster-agent-controller-cleanup': 'true',
        'lifecycle.cattle.io/create.cluster-provisioner-controller': 'true',
        'lifecycle.cattle.io/create.cluster-scoped-gc': 'true',
        'lifecycle.cattle.io/create.mgmt-cluster-rbac-remove': 'true',
        'management.cattle.io/current-cluster-controllers-version': 'v1.27.10+rke2r1',
        'objectset.rio.cattle.io/applied':
          'H4sIAAAAAAAA/4xSwWrcQAz9laKzvdl1mmVr6CGEHkJpGmhpz7JH9qoea4xG9jaE/HsZrzddUhJ6GkbSk96T3iPgwD9IIweBEnoUbKknsVWNZp5WHC6mS8igY3FQwo0fo5FCBj0ZOjSE8hFQJBgaB4np2zB5d9agVkILepsajJE098207SCDUP2i2iLZSjmcAThV1sdR+YymN6rDQUjzduqghEHDxEkMS3suYZO9+8ziPv7l/3Y3wZ6gBPT0OzeKlmtHRe7CfwHjgHVCN57IckcNjt4ge40cup6FoykaJeGmI8FTBrNwDvKde4qG/QCljN5n4LEiP2/6NS57jHsoYbdZF9RsN+vNdldR3VSbXVG4y6vKbd32/Ydme1lsNlU1T1sU13mf69V0NUnRpHAcqJ5P3JLYbY8tfZ1IlV0qhgxQ4oE0kUmMj9v9RrWSLTFHsVYe7GgwmAOs5K6fG0IJilLvSS+WN5+nlVOx2q2KM8ho+5eIbqwox4FzHG1fTutVsVonBMfB48Pd62ckwcrT4odrT2osLZQN+kgvsl+CsAX9N39Hdgja3QfP9cPpOvPVfwbtZhssDF5agfshqJG7CdJwmxachJx+kDbPYqSC/nmmDzX6E+HR9p/EDYHFEvrIxy21TxkcWFw4xHulhpTcyfdL/ulPAAAA///HOsOL+AMAAA',
        'objectset.rio.cattle.io/id': 'cluster-create',
        'objectset.rio.cattle.io/owner-gvk': 'provisioning.cattle.io/v1, Kind=Cluster',
        'objectset.rio.cattle.io/owner-name': provClusterId,
        'objectset.rio.cattle.io/owner-namespace': `${namespace}`,
        'provisioning.cattle.io/administrated': 'true',
      },
      creationTimestamp: '2024-03-07T15:45:25Z',
      fields: [mgmtClusterId, '19h'],
      finalizers: [
        'wrangler.cattle.io/mgmt-cluster-remove',
        'controller.cattle.io/cluster-agent-controller-cleanup',
        'controller.cattle.io/cluster-scoped-gc',
        'controller.cattle.io/cluster-provisioner-controller',
        'controller.cattle.io/mgmt-cluster-rbac-remove',
      ],
      generation: 42,
      labels: {
        'objectset.rio.cattle.io/hash': '8102ef610168becfb1822d35bd6d649f63211bbe',
        'provider.cattle.io': 'rke2',
      },
      name: mgmtClusterId,
      relationships: [
        {
          fromId: `${namespace}/${provClusterId}`,
          fromType: 'provisioning.cattle.io.cluster',
          rel: 'applies',
          state: 'active',
          message: 'Resource is Ready',
        },
        {
          toId: `${mgmtClusterId}-clustermember`,
          toType: 'rbac.authorization.k8s.io.clusterrole',
          rel: 'owner',
          state: 'active',
          message: 'Resource is current',
        },
        {
          toId: `${mgmtClusterId}-clusterowner`,
          toType: 'rbac.authorization.k8s.io.clusterrole',
          rel: 'owner',
          state: 'active',
          message: 'Resource is current',
        },
        {
          toId: 'cattle-global-data/cluster-serviceaccounttoken-r5kvb',
          toType: 'secret',
          rel: 'owner',
          state: 'active',
          message: 'Resource is always ready',
        },
        {
          toId: 'cattle-global-data/cluster-serviceaccounttoken-mmcf9',
          toType: 'secret',
          rel: 'owner',
          state: 'active',
          message: 'Resource is always ready',
        },
      ],
      resourceVersion: SAFE_RESOURCE_REVISION,
      state: {
        error: false,
        message: 'Resource is Ready',
        name: 'active',
        transitioning: false,
      },
      uid: '5887e0fe-d20a-42cc-812e-cbc2213201fe',
    },
    spec: {
      agentImageOverride: '',
      answers: {},
      clusterSecrets: {},
      description: '',
      desiredAgentImage: 'rancher/rancher-agent:v2.8.2',
      desiredAuthImage: 'rancher/kube-api-auth:v0.2.0',
      displayName: provClusterId,
      enableClusterAlerting: false,
      enableClusterMonitoring: false,
      enableNetworkPolicy: null,
      fleetWorkspaceName: `${namespace}`,
      importedConfig: { kubeConfig: '' },
      internal: false,
      localClusterAuthEndpoint: { enabled: false },
      windowsPreferedCluster: false,
    },
    status: {
      agentFeatures: {
        'embedded-cluster-api': false,
        fleet: false,
        monitoringv1: false,
        'multi-cluster-management': false,
        'multi-cluster-management-agent': true,
        provisioningv2: false,
        rke2: false,
      },
      agentImage: 'rancher/rancher-agent:v2.8.2',
      aksStatus: {
        privateRequiresTunnel: null,
        rbacEnabled: null,
        upstreamSpec: null,
      },
      allocatable: {
        cpu: '2',
        memory: '4026036Ki',
        pods: '110',
      },
      apiEndpoint: 'https://10.43.0.1:443',
      appliedAgentEnvVars: [
        {
          name: 'CATTLE_SERVER_VERSION',
          value: 'v2.8.2',
        },
        {
          name: 'CATTLE_INSTALL_UUID',
          value: 'ccf7f3e1-92b6-4ca3-80ff-dd632a8f818d',
        },
        {
          name: 'CATTLE_INGRESS_IP_DOMAIN',
          value: 'sslip.io',
        },
      ],
      appliedEnableNetworkPolicy: false,
      appliedPodSecurityPolicyTemplateId: '',
      appliedSpec: {
        agentImageOverride: '',
        answers: {},
        clusterSecrets: {},
        description: '',
        desiredAgentImage: '',
        desiredAuthImage: '',
        displayName: '',
        enableClusterAlerting: false,
        enableClusterMonitoring: false,
        enableNetworkPolicy: null,
        internal: false,
        localClusterAuthEndpoint: { enabled: false },
        windowsPreferedCluster: false,
      },
      authImage: '',
      caCert:
        'LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJlRENDQVIrZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWtNU0l3SUFZRFZRUUREQmx5YTJVeUxYTmwKY25abGNpMWpZVUF4TnpBNU9ESTJORGd5TUI0WERUSTBNRE13TnpFMU5EZ3dNbG9YRFRNME1ETXdOVEUxTkRndwpNbG93SkRFaU1DQUdBMVVFQXd3WmNtdGxNaTF6WlhKMlpYSXRZMkZBTVRjd09UZ3lOalE0TWpCWk1CTUdCeXFHClNNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJJNnVnTGpqbXJwbHJyVEsrOE5LWUFRb3FRNXdLZ1cvQ1Y1UWoraEIKUkNLQXJxaVAveEM3NStSdGpqb1haaTRBRTVuWlRkbDBkYVZwSmdPOEp1R00yY1NqUWpCQU1BNEdBMVVkRHdFQgovd1FFQXdJQ3BEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01CMEdBMVVkRGdRV0JCVFUvbG5SSklNN1hWSnFodDhICjI1ZDUyVFVtMERBS0JnZ3Foa2pPUFFRREFnTkhBREJFQWlBc0luZGRxd21Ub2JWbk9INndhVnhMTzA4bDNDQVQKdWg2bGZyd3dDTTdZRWdJZ1NMNlZtdHhFZkRCd0wweTU4TjNFdnl3VXl4U0FuZDBzMCtQRVFON0FwUm89Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K',
      capabilities: { loadBalancerCapabilities: {} },
      capacity: {
        cpu: '2',
        memory: '4026036Ki',
        pods: '110',
      },
      conditions: [
        {
          error: false,
          lastUpdateTime: '2024-03-07T15:45:26Z',
          status: 'True',
          transitioning: false,
          type: 'BackingNamespaceCreated',
        },
        {
          error: false,
          lastUpdateTime: '2024-03-07T15:45:26Z',
          status: 'True',
          transitioning: false,
          type: 'DefaultProjectCreated',
        },
        {
          error: false,
          lastUpdateTime: '2024-03-07T15:45:26Z',
          status: 'True',
          transitioning: false,
          type: 'SystemProjectCreated',
        },
        {
          error: false,
          lastUpdateTime: '2024-03-07T15:45:26Z',
          status: 'True',
          transitioning: false,
          type: 'InitialRolesPopulated',
        },
        {
          error: false,
          lastUpdateTime: '2024-03-07T15:52:29Z',
          status: 'True',
          transitioning: false,
          type: 'Connected',
        },
        {
          error: false,
          lastUpdateTime: '2024-03-07T15:45:30Z',
          status: 'True',
          transitioning: false,
          type: 'CreatorMadeOwner',
        },
        {
          error: false,
          lastUpdateTime: '2024-03-07T15:52:47Z',
          status: 'True',
          transitioning: false,
          type: 'Updated',
        },
        {
          error: false,
          lastUpdateTime: '2024-03-07T15:45:32Z',
          status: 'True',
          transitioning: false,
          type: 'Provisioned',
        },
        {
          error: false,
          lastUpdateTime: '2024-03-07T15:45:34Z',
          status: 'True',
          transitioning: false,
          type: 'NoDiskPressure',
        },
        {
          error: false,
          lastUpdateTime: '2024-03-07T15:45:34Z',
          status: 'True',
          transitioning: false,
          type: 'NoMemoryPressure',
        },
        {
          error: false,
          lastUpdateTime: '2024-03-07T15:45:34Z',
          status: 'True',
          transitioning: false,
          type: 'SecretsMigrated',
        },
        {
          error: false,
          lastUpdateTime: '2024-03-07T15:45:34Z',
          status: 'True',
          transitioning: false,
          type: 'ServiceAccountSecretsMigrated',
        },
        {
          error: false,
          lastUpdateTime: '2024-03-07T15:45:34Z',
          status: 'True',
          transitioning: false,
          type: 'RKESecretsMigrated',
        },
        {
          error: false,
          lastUpdateTime: '2024-03-07T15:45:35Z',
          status: 'True',
          transitioning: false,
          type: 'ACISecretsMigrated',
        },
        {
          error: false,
          lastUpdateTime: '2024-03-07T15:52:44Z',
          status: 'True',
          transitioning: false,
          type: 'Ready',
        },
        {
          error: false,
          lastUpdateTime: '2024-03-07T15:51:59Z',
          status: 'True',
          transitioning: false,
          type: 'GlobalAdminsSynced',
        },
        {
          error: false,
          lastUpdateTime: '2024-03-07T15:52:04Z',
          status: 'True',
          transitioning: false,
          type: 'SystemAccountCreated',
        },
        {
          error: false,
          lastUpdateTime: '2024-03-07T15:52:17Z',
          status: 'True',
          transitioning: false,
          type: 'AgentDeployed',
        },
        {
          error: false,
          lastUpdateTime: '2024-03-07T15:52:44Z',
          status: 'True',
          transitioning: false,
          type: 'Waiting',
        },
      ],
      driver: 'digitalocean',
      eksStatus: {
        generatedNodeRole: '',
        managedLaunchTemplateID: '',
        managedLaunchTemplateVersions: null,
        privateRequiresTunnel: null,
        securityGroups: null,
        subnets: null,
        upstreamSpec: null,
        virtualNetwork: '',
      },
      gkeStatus: {
        privateRequiresTunnel: null,
        upstreamSpec: null,
      },
      info: {
        arch: 'amd64',
        kubernetesVersion: 'v1.35.3+rke2r3',
        machineProvider: 'Digitalocean',
        nodeCount: 2,
        provisioningClusterRef: {
          apiVersion: 'provisioning.cattle.io/v1',
          kind: 'Cluster',
          name: `${provClusterId}`,
          namespace: `${namespace}`,
        },
      },
      limits: {
        cpu: '200m',
        memory: '192Mi',
        pods: '0',
      },
      linuxWorkerCount: 1,
      nodeCount: 1,
      provider: 'rke2',
      requested: {
        cpu: '1325m',
        memory: '2410Mi',
        pods: '20',
      },
      serviceAccountTokenSecret: 'cluster-serviceaccounttoken-r5kvb',
      version: {
        buildDate: '2024-01-17T21:34:35Z',
        compiler: 'gc',
        gitCommit: '0fa26aea1d5c21516b0d96fea95a77d8d429912e',
        gitTreeState: 'clean',
        gitVersion: 'v1.27.10+rke2r1',
        goVersion: 'go1.20.13 X:boringcrypto',
        major: '1',
        minor: '27',
        platform: 'linux/amd64',
      },
    },
  };
}
