import { CYPRESS_SAFE_RESOURCE_REVISION } from '../../blueprint.utils';

export const eventsGetEmptyEventsSet = {
  type: 'collection',
  links: { self: '/v1/events' },
  createTypes: { event: '/v1/events' },
  actions: {},
  resourceType: 'event',
  revision: CYPRESS_SAFE_RESOURCE_REVISION,
  data: [],
};

export const eventsGetResponseSmallSet = {
  type: 'collection',
  links: { self: '/v1/events' },
  createTypes: { event: '/v1/events' },
  actions: {},
  resourceType: 'event',
  revision: CYPRESS_SAFE_RESOURCE_REVISION,
  count: 3,
  data: [
    {
      id: 'cattle-fleet-local-system/fleet-agent-0.17d80b90a6d2c7ab',
      type: 'event',
      _type: 'dummy_data',
      apiVersion: 'v1',
      metadata: {
        fields: [
          '7m',
          'Normal',
          'Killing',
          'pod/fleet-agent-0',
          'spec.containers{fleet-agent}',
          'kubelet, ip-172-31-2-245.us-east-2.compute.internal',
          'Stopping container fleet-agent',
          '7m',
          1,
          'fleet-agent-0.17d80b90a6d2c7ab',
        ],
        name: 'fleet-agent-0.17d80b90a6d2c7ab',
        namespace: 'cattle-fleet-local-system',
        relationships: null,
        resourceVersion: CYPRESS_SAFE_RESOURCE_REVISION,
        state: { error: false, message: 'Resource is current', name: 'active', transitioning: false },
      },
      reason: 'e2e-vai-regression-test',
    },
    {
      id: 'cattle-fleet-local-system/fleet-agent-1.17d80b90a6d2c7ac',
      type: 'event',
      _type: 'dummy_data',
      apiVersion: 'v1',
      metadata: {
        fields: [
          '7m',
          'Normal',
          'Killing',
          'pod/fleet-agent-1',
          'spec.containers{fleet-agent}',
          'kubelet, ip-172-31-2-245.us-east-2.compute.internal',
          'Stopping container fleet-agent',
          '7m',
          1,
          'fleet-agent-1.17d80b90a6d2c7ac',
        ],
        name: 'fleet-agent-1.17d80b90a6d2c7ac',
        namespace: 'cattle-fleet-local-system',
        relationships: null,
        resourceVersion: CYPRESS_SAFE_RESOURCE_REVISION,
        state: { error: false, message: 'Resource is current', name: 'active', transitioning: false },
      },
      reason: 'e2e-vai-regression-test',
    },
    {
      id: 'cattle-fleet-local-system/fleet-agent-2.17d80b90a6d2c7ad',
      type: 'event',
      _type: 'dummy_data',
      apiVersion: 'v1',
      metadata: {
        fields: [
          '7m',
          'Normal',
          'Killing',
          'pod/fleet-agent-2',
          'spec.containers{fleet-agent}',
          'kubelet, ip-172-31-2-245.us-east-2.compute.internal',
          'Stopping container fleet-agent',
          '7m',
          1,
          'fleet-agent-2.17d80b90a6d2c7ad',
        ],
        name: 'fleet-agent-2.17d80b90a6d2c7ad',
        namespace: 'cattle-fleet-local-system',
        relationships: null,
        resourceVersion: CYPRESS_SAFE_RESOURCE_REVISION,
        state: { error: false, message: 'Resource is current', name: 'active', transitioning: false },
      },
      reason: 'e2e-vai-regression-test',
    },
  ],
};
