import { SAFE_RESOURCE_REVISION } from '../../blueprint.utils';

export const serviceAccGetResponseEmpty = {
  type: 'collection',
  links: { self: '/v1/serviceaccounts' },
  createTypes: { serviceaccount: '/v1/serviceaccounts' },
  actions: {},
  resourceType: 'serviceaccount',
  revision: SAFE_RESOURCE_REVISION,
  count: 0,
  data: [],
};

export const serviceAcctResponseSmallSet = {
  type: 'collection',
  links: { self: '/v1/serviceaccounts' },
  createTypes: { serviceaccount: '/v1/serviceaccounts' },
  actions: {},
  resourceType: 'serviceaccount',
  revision: SAFE_RESOURCE_REVISION,
  count: 3,
  data: [
    {
      id: 'cattle-system/default',
      type: 'serviceaccount',
      links: {
        remove: '/v1/serviceaccounts/cattle-system/default',
        self: '/v1/serviceaccounts/cattle-system/default',
        update: '/v1/serviceaccounts/cattle-system/default',
        view: '/api/v1/namespaces/cattle-system/serviceaccounts/default',
      },
      apiVersion: 'v1',
      automountServiceAccountToken: false,
      kind: 'ServiceAccount',
      metadata: {
        creationTimestamp: '2024-06-18T15:41:39Z',
        fields: ['default', 0, '6h13m'],
        name: 'default',
        namespace: 'cattle-system',
        relationships: null,
        resourceVersion: SAFE_RESOURCE_REVISION,
        state: { error: false, message: 'Resource is current', name: 'active', transitioning: false },
        uid: 'a60fc248-faea-47d7-a2f5-d7bf759c48ad',
      },
    },
    {
      id: 'cattle-fleet-local-system/default',
      type: 'serviceaccount',
      links: {
        remove: '/v1/serviceaccounts/cattle-fleet-local-system/default',
        self: '/v1/serviceaccounts/cattle-fleet-local-system/default',
        update: '/v1/serviceaccounts/cattle-fleet-local-system/default',
        view: '/api/v1/namespaces/cattle-fleet-local-system/serviceaccounts/default',
      },
      apiVersion: 'v1',
      automountServiceAccountToken: false,
      kind: 'ServiceAccount',
      metadata: {
        creationTimestamp: '2024-06-18T15:48:26Z',
        fields: ['default', 0, '6h6m'],
        name: 'default',
        namespace: 'cattle-fleet-local-system',
        relationships: null,
        resourceVersion: SAFE_RESOURCE_REVISION,
        state: { error: false, message: 'Resource is current', name: 'active', transitioning: false },
        uid: '003b0146-d4c0-4ae8-8736-2183d675ebc9',
      },
    },
    {
      id: 'cattle-fleet-local-system/fleet-agent',
      type: 'serviceaccount',
      links: {
        remove: '/v1/serviceaccounts/cattle-fleet-local-system/fleet-agent',
        self: '/v1/serviceaccounts/cattle-fleet-local-system/fleet-agent',
        update: '/v1/serviceaccounts/cattle-fleet-local-system/fleet-agent',
        view: '/api/v1/namespaces/cattle-fleet-local-system/serviceaccounts/fleet-agent',
      },
      apiVersion: 'v1',
      kind: 'ServiceAccount',
      metadata: {
        creationTimestamp: '2024-06-18T15:48:28Z',
        fields: ['fleet-agent', 0, '6h6m'],
        name: 'fleet-agent',
        namespace: 'cattle-fleet-local-system',
        relationships: null,
        resourceVersion: SAFE_RESOURCE_REVISION,
        state: { error: false, message: 'Resource is current', name: 'active', transitioning: false },
        uid: 'de615799-099c-4088-809c-8cf00122c0fa',
      },
    },
  ],
};
