#!/usr/bin/env npx tsx
/**
 * Generate docs/ASSERTION-GAP-MAP.md — compares upstream Cypress specs
 * against Playwright specs to find missing tests and unconverted suites.
 *
 * For each spec file, extracts test names (it/test calls) and matches
 * by directory + filename across repos.
 *
 * Usage:
 *   npx tsx scripts/generate-gap-map.ts
 *   yarn gap-map
 */

import * as fs from 'fs';
import * as path from 'path';

const PW_TEST_ROOT = path.resolve('e2e/tests');
const UPSTREAM_TEST_ROOT = path.resolve('../dashboard/cypress/e2e/tests');
const OUTPUT = path.resolve('docs/ASSERTION-GAP-MAP.md');

interface SpecEntry {
  filePath: string;
  relativePath: string;
  suite: string;
  tests: string[];
  skippedTests: string[];
}

function extractTests(filePath: string, pattern: RegExp, skipPattern: RegExp): { tests: string[]; skipped: string[] } {
  const src = fs.readFileSync(filePath, 'utf-8');
  const tests: string[] = [];
  const skipped: string[] = [];
  let m;

  while ((m = pattern.exec(src)) !== null) {
    tests.push(m[1]);
  }

  while ((m = skipPattern.exec(src)) !== null) {
    skipped.push(m[1]);
  }

  return { tests, skipped };
}

function collectSpecs(dir: string, root: string): SpecEntry[] {
  if (!fs.existsSync(dir)) {
    return [];
  }

  const results: SpecEntry[] = [];
  const entries = fs.readdirSync(dir, { withFileTypes: true });

  for (const entry of entries) {
    const full = path.join(dir, entry.name);

    if (entry.isDirectory()) {
      results.push(...collectSpecs(full, root));
    } else if (entry.name.endsWith('.spec.ts')) {
      const rel = path.relative(root, full);
      const suite = rel.split(path.sep).slice(0, -1).join('/');

      results.push({
        filePath: full,
        relativePath: rel,
        suite: suite || 'root',
        tests: [],
        skippedTests: [],
      });
    }
  }

  return results.sort((a, b) => a.relativePath.localeCompare(b.relativePath));
}

/** Normalize spec path for matching across repos */
function normalizeSpecPath(relativePath: string): string {
  return relativePath
    .replace(/^pages\//, '')
    .replace(/^e2e\/tests\//, '')
    .replace(/\.spec\.ts$/, '');
}

// --- Main ---

if (!fs.existsSync(UPSTREAM_TEST_ROOT)) {
  console.error(`Upstream test root not found: ${UPSTREAM_TEST_ROOT}`);
  console.error('Ensure ../dashboard/cypress/e2e/tests/ exists.');
  process.exit(1);
}

// Collect specs
const pwSpecs = collectSpecs(PW_TEST_ROOT, PW_TEST_ROOT);
const upstreamSpecs = collectSpecs(UPSTREAM_TEST_ROOT, UPSTREAM_TEST_ROOT);

// Extract test names
const itPattern = /\bit\(\s*['"`]([^'"`]+)['"`]/g;
const itSkipPattern = /\bit\.skip\(\s*['"`]([^'"`]+)['"`]/g;
const testPattern = /\btest\(\s*['"`]([^'"`]+)['"`]/g;
const testSkipPattern = /\btest\.skip\(\s*(?:true\s*,\s*)?['"`]([^'"`]+)['"`]/g;

for (const spec of upstreamSpecs) {
  const { tests, skipped } = extractTests(spec.filePath, itPattern, itSkipPattern);

  spec.tests = tests;
  spec.skippedTests = skipped;
}

for (const spec of pwSpecs) {
  const { tests, skipped } = extractTests(spec.filePath, testPattern, testSkipPattern);

  spec.tests = tests;
  spec.skippedTests = skipped;
}

// Build lookup by normalized path
const pwByPath = new Map<string, SpecEntry>();

for (const spec of pwSpecs) {
  pwByPath.set(normalizeSpecPath(spec.relativePath), spec);
}

const upstreamByPath = new Map<string, SpecEntry>();

for (const spec of upstreamSpecs) {
  upstreamByPath.set(normalizeSpecPath(spec.relativePath), spec);
}

// Group upstream specs by suite
const suites = new Map<string, SpecEntry[]>();

for (const spec of upstreamSpecs) {
  const suite = spec.suite || 'root';

  if (!suites.has(suite)) {
    suites.set(suite, []);
  }
  suites.get(suite)!.push(spec);
}

// Generate output
const lines: string[] = [
  '<!-- AUTO-GENERATED by scripts/generate-gap-map.ts — do not edit manually -->',
  '# Assertion Gap Map',
  '',
  `Generated: ${new Date().toISOString().split('T')[0]}`,
  '',
  `Upstream Cypress: ${upstreamSpecs.length} specs, ${upstreamSpecs.reduce((s, e) => s + e.tests.length, 0)} tests`,
  `Playwright: ${pwSpecs.length} specs, ${pwSpecs.reduce((s, e) => s + e.tests.length, 0)} tests`,
  '',
];

// Summary table
lines.push('## Summary');
lines.push('');
lines.push('| Suite | Upstream Specs | Upstream Tests | PW Specs | PW Tests | Converted |');
lines.push('|-------|---------------|----------------|----------|----------|-----------|');

let totalUpSpecs = 0;
let totalUpTests = 0;
let totalPwSpecs = 0;
let totalPwTests = 0;

for (const [suite, specs] of [...suites].sort((a, b) => a[0].localeCompare(b[0]))) {
  const upSpecCount = specs.length;
  const upTestCount = specs.reduce((s, e) => s + e.tests.length, 0);

  let pwSpecCount = 0;
  let pwTestCount = 0;

  for (const spec of specs) {
    const norm = normalizeSpecPath(spec.relativePath);
    const pw = pwByPath.get(norm);

    if (pw) {
      pwSpecCount++;
      pwTestCount += pw.tests.length;
    }
  }

  const pct = upTestCount > 0 ? Math.round((pwTestCount / upTestCount) * 100) : 0;
  const status = pct === 100 ? '✅' : pct > 0 ? `${pct}%` : '—';

  lines.push(`| ${suite} | ${upSpecCount} | ${upTestCount} | ${pwSpecCount} | ${pwTestCount} | ${status} |`);

  totalUpSpecs += upSpecCount;
  totalUpTests += upTestCount;
  totalPwSpecs += pwSpecCount;
  totalPwTests += pwTestCount;
}

// PW-only specs (no upstream equivalent)
const pwOnlySpecs = pwSpecs.filter((s) => !upstreamByPath.has(normalizeSpecPath(s.relativePath)));

if (pwOnlySpecs.length > 0) {
  const pwOnlyTests = pwOnlySpecs.reduce((s, e) => s + e.tests.length, 0);

  lines.push(`| *PW-only specs* | — | — | ${pwOnlySpecs.length} | ${pwOnlyTests} | — |`);
  totalPwSpecs += pwOnlySpecs.length;
  totalPwTests += pwOnlyTests;
}

const totalPct = totalUpTests > 0 ? Math.round((totalPwTests / totalUpTests) * 100) : 0;

lines.push(
  `| **TOTAL** | **${totalUpSpecs}** | **${totalUpTests}** | **${totalPwSpecs}** | **${totalPwTests}** | **${totalPct}%** |`,
);
lines.push('');

// Per-suite detail: unconverted specs
lines.push('## Unconverted Specs');
lines.push('');

let hasUnconverted = false;

for (const [suite, specs] of [...suites].sort((a, b) => a[0].localeCompare(b[0]))) {
  const unconverted = specs.filter((s) => !pwByPath.has(normalizeSpecPath(s.relativePath)));

  if (unconverted.length === 0) {
    continue;
  }
  hasUnconverted = true;

  lines.push(`### ${suite}`);
  lines.push('');
  lines.push('| Spec | Tests | Skipped |');
  lines.push('|------|-------|---------|');

  for (const spec of unconverted) {
    const file = path.basename(spec.relativePath);

    lines.push(`| ${file} | ${spec.tests.length} | ${spec.skippedTests.length} |`);
  }

  lines.push('');
}

if (!hasUnconverted) {
  lines.push('All upstream specs have Playwright equivalents.');
  lines.push('');
}

// Per-suite detail: converted specs with test count diff
lines.push('## Converted Specs (test count comparison)');
lines.push('');
lines.push('| Spec | Upstream Tests | PW Tests | Delta |');
lines.push('|------|---------------|----------|-------|');

for (const spec of upstreamSpecs) {
  const norm = normalizeSpecPath(spec.relativePath);
  const pw = pwByPath.get(norm);

  if (!pw) {
    continue;
  }

  const delta = pw.tests.length - spec.tests.length;
  const deltaStr = delta === 0 ? '—' : delta > 0 ? `+${delta}` : `${delta}`;

  if (delta !== 0) {
    lines.push(`| ${spec.relativePath} | ${spec.tests.length} | ${pw.tests.length} | ${deltaStr} |`);
  }
}

lines.push('');

const output = lines.join('\n');

fs.mkdirSync(path.dirname(OUTPUT), { recursive: true });
fs.writeFileSync(OUTPUT, output);
console.log(`Gap map updated: ${OUTPUT}`);
console.log(`  Upstream: ${totalUpSpecs} specs, ${totalUpTests} tests`);
console.log(`  Playwright: ${totalPwSpecs} specs, ${totalPwTests} tests (${totalPct}%)`);
