#!/usr/bin/env npx tsx
/**
 * Generate e2e/po/INDEX.md — a machine-readable index of all Page Objects.
 *
 * For each .po.ts file, extracts:
 *   - Class name (default export or named export)
 *   - Parent class (extends X)
 *   - Key public methods (async methods, self(), goTo(), etc.)
 *   - Constructor selector (if visible in source)
 *
 * This index is cheap to read (~2-3KB) and saves agents from scanning 100+ PO files.
 *
 * Usage:
 *   npx tsx scripts/generate-po-index.ts
 *
 * Runs automatically via pre-commit hook.
 */

import * as fs from 'fs';
import * as path from 'path';

const PO_ROOT = path.resolve('e2e/po');
const OUTPUT = path.join(PO_ROOT, 'INDEX.md');

interface PoEntry {
  filePath: string;
  relativePath: string;
  className: string;
  extendsClass: string | null;
  selector: string | null;
  methods: string[];
}

function extractPoInfo(filePath: string, relativePath: string): PoEntry | null {
  const src = fs.readFileSync(filePath, 'utf-8');

  // Extract class name — default export or named export
  const classMatch = src.match(/(?:export\s+default\s+)?class\s+(\w+)(?:\s+extends\s+(\w+))?/);

  if (!classMatch) {
    return null;
  }

  const className = classMatch[1];
  const extendsClass = classMatch[2] || null;

  // Extract constructor selector — super(page, 'selector') or this.selector = 'x'
  let selector: string | null = null;
  const superMatch = src.match(/super\(\s*page\s*,\s*['"`]([^'"`]+)['"`]/);

  if (superMatch) {
    selector = superMatch[1];
  } else {
    const selectorMatch = src.match(/this\.selector\s*=\s*['"`]([^'"`]+)['"`]/);

    if (selectorMatch) {
      selector = selectorMatch[1];
    }
  }

  // Extract public async methods + key non-async methods
  const methods: string[] = [];
  const methodRegex = /^\s+(?:async\s+)?(\w+)\s*\([^)]*\)/gm;
  let m;

  while ((m = methodRegex.exec(src)) !== null) {
    const name = m[1];

    // Skip constructor, private-convention, and inherited base methods
    if (name === 'constructor') {
      continue;
    }
    if (name.startsWith('_')) {
      continue;
    }

    methods.push(name);
  }

  // Deduplicate
  const uniqueMethods = [...new Set(methods)];

  return {
    filePath,
    relativePath,
    className,
    extendsClass,
    selector,
    methods: uniqueMethods,
  };
}

function collectPoFiles(dir: string, root: string): string[] {
  const results: string[] = [];
  const entries = fs.readdirSync(dir, { withFileTypes: true });

  for (const entry of entries) {
    const full = path.join(dir, entry.name);

    if (entry.isDirectory()) {
      results.push(...collectPoFiles(full, root));
    } else if (entry.name.endsWith('.po.ts')) {
      results.push(full);
    }
  }

  return results.sort();
}

function formatIndex(entries: PoEntry[]): string {
  const lines: string[] = [
    '<!-- AUTO-GENERATED by scripts/generate-po-index.ts — do not edit manually -->',
    '# Page Object Index',
    '',
    `${entries.length} Page Objects indexed.`,
    '',
  ];

  // Group by directory
  const groups = new Map<string, PoEntry[]>();

  for (const e of entries) {
    const dir = path.dirname(e.relativePath);

    if (!groups.has(dir)) {
      groups.set(dir, []);
    }
    groups.get(dir)!.push(e);
  }

  for (const [dir, pos] of groups) {
    lines.push(`## ${dir}/`);
    lines.push('');
    lines.push('| Class | File | Extends | Selector | Methods |');
    lines.push('|-------|------|---------|----------|---------|');

    for (const po of pos) {
      const file = path.basename(po.relativePath);
      const ext = po.extendsClass || '—';
      const sel = po.selector ? `\`${po.selector}\`` : '—';
      const meths =
        po.methods.length > 0
          ? po.methods.slice(0, 8).join(', ') + (po.methods.length > 8 ? ` (+${po.methods.length - 8})` : '')
          : '—';

      lines.push(`| ${po.className} | ${file} | ${ext} | ${sel} | ${meths} |`);
    }

    lines.push('');
  }

  return lines.join('\n');
}

// --- Main ---
const poFiles = collectPoFiles(PO_ROOT, PO_ROOT);
const entries: PoEntry[] = [];

for (const file of poFiles) {
  const rel = path.relative(PO_ROOT, file);
  const entry = extractPoInfo(file, rel);

  if (entry) {
    entries.push(entry);
  }
}

const output = formatIndex(entries);

// Check if content changed before writing (avoids dirty git state in pre-commit)
const existing = fs.existsSync(OUTPUT) ? fs.readFileSync(OUTPUT, 'utf-8') : '';

if (existing === output) {
  console.log('PO index is up to date.');
  process.exit(0);
}

fs.writeFileSync(OUTPUT, output);
console.log(`PO index updated: ${entries.length} entries written to ${OUTPUT}`);
